"""sync_projects_table

Revision ID: f3b140a88240
Revises: eb5bffec4c29
Create Date: 2026-02-23 22:12:55.143069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3b140a88240'
down_revision: Union[str, Sequence[str], None] = 'eb5bffec4c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('cours', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cours', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cours', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_cours_id'), 'cours', ['id'], unique=False)
    op.drop_constraint('courses_profile_id_fkey', 'cours', type_='foreignkey')
    op.create_foreign_key(None, 'cours', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('distinctions', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('distinctions', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('distinctions', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('distinctions', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_distinctions_id'), 'distinctions', ['id'], unique=False)
    op.drop_constraint('distinctions_profile_id_fkey', 'distinctions', type_='foreignkey')
    op.create_foreign_key(None, 'distinctions', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('media_artefacts', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.add_column('media_artefacts', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'media_artefacts', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('profiles', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('profiles', 'grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profiles', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('projects', 'coauthor',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('idx_projects_profile', table_name='projects')
    op.drop_index('idx_projects_profile_id', table_name='projects')
    op.alter_column('publications', 'coauthor',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('idx_publications_profile_id', table_name='publications')
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'inactive'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.create_index('idx_publications_profile_id', 'publications', ['profile_id'], unique=False)
    op.alter_column('publications', 'coauthor',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index('idx_projects_profile_id', 'projects', ['profile_id'], unique=False)
    op.create_index('idx_projects_profile', 'projects', ['profile_id'], unique=False)
    op.alter_column('projects', 'coauthor',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('projects', 'created_at')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='unique')
    op.alter_column('profiles', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('profiles', 'grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'created_at')
    op.drop_column('profiles', 'profile_picture')
    op.drop_constraint(None, 'media_artefacts', type_='foreignkey')
    op.drop_column('media_artefacts', 'description')
    op.drop_column('media_artefacts', 'profile_id')
    op.drop_constraint(None, 'distinctions', type_='foreignkey')
    op.create_foreign_key('distinctions_profile_id_fkey', 'distinctions', 'profiles', ['profile_id'], ['id'])
    op.drop_index(op.f('ix_distinctions_id'), table_name='distinctions')
    op.alter_column('distinctions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('distinctions', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('distinctions', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('distinctions', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.create_foreign_key('courses_profile_id_fkey', 'cours', 'profiles', ['profile_id'], ['id'])
    op.drop_index(op.f('ix_cours_id'), table_name='cours')
    op.alter_column('cours', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('cours', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cours', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
