"""fix profiles nullable names and add sender_name to messages

Revision ID: 30b13eb432d8
Revises: 82402fc6ea39
Create Date: 2026-01-31 10:46:24.616632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b13eb432d8'
down_revision: Union[str, Sequence[str], None] = '82402fc6ea39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audits')
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.add_column('messages', sa.Column('sender_name', sa.String(length=100), nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('messages', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'sender_name')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.create_index(op.f('ix_audit_logs_id'), 'audits', ['id'], unique=False)
    # ### end Alembic commands ###
